### ISSUE TITLE
White LED is always ON with 4-colours-in-1-LED (5050 RGBW)

### ISSUE THREAD

**Issue by mankron** [corbanmailloux/esp-mqtt-rgb-led#64]
Hi, first thank you for your great job!

I use the MQTT RGBW Solution and don't know if there's an issue with my hardware or the code.

The LED I use is the "BTF-LIGHTING 5050 RGBW" (amzn) which has 4 colours in 1 LED. 

Your Code

```
enum strip {
  BRIGHTNESS, // only one color/only white
  RGB,        // RGB LEDs
  RGBW        // RGB LEDs with an extra white LED per LED       X   <-----
};
```

looks like it means such an LED. Am I right or do you know if this type of LED is not supported?

My HA (actual release) config is:

- Home Assistant 2023.9.1 
- Supervisor 2023.08.3 
- Operating System 10.5 
- Frontend 20230908.0 - latest 

Config-Yaml:

```
mqtt:
  light:
     schema: json
     name: xxx_TV_RGBW
     state_topic: "xxx/esp01/rgbwTV"
     command_topic: "xxx/esp01/rgbwTV/set"
     brightness: true
     color_mode: true
     supported_color_modes: ["rgbw"]
     effect: true
     effect_list: [colorfade_slow, colorfade_fast, flash]
     optimistic: false
     qos: 0
```

It's working but the colour white is always on. 

Fun fact: During the effects the white LED goes out, in normal mode it's always on, I can't turn it off.
You cannot produce intense RGB colors with the white LED switched on.
Is there a way to turn off the white content using an extra switch or something?
